# Generated by Django 2.2.5 on 2019-09-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('title', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('main_image', models.ImageField(upload_to='')),
                ('thumb_image', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('position', models.IntegerField(default=-1)),
            ],
        ),
    ]
