version: '3'

services:
  dbhost:
    environment:
      POSTGRES_PASSWORD: dumbpassword
      POSTGRES_USER: alloydflanagan
    image: postgres:alpine
    volumes:
      - alloydflanagan_data:/var/lib/postgresql/data
  website:
    image: alflanagan/alloydflanagan
    environment:
      PYTHONPATH: /usr/src/app/alloydflanagan/
    command: pipenv run ./manage.py migrate
    depends_on:
      - dbhost
    ports:
      - "3000:2450"
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "2450:3000"
      - "80:80"
      - "443:443"
volumes:
  alloydflanagan_data: {}
